### ISSUE TITLE
Referral tracking parameter

### ISSUE THREAD

**Issue by jaredkotoff** [YOURLS/YOURLS#3659]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Track a parameter on the end of short urls to allow tracking of where those link were clicked from.

Examples: `myourls.com/hello?ref=qrcode` or `myourls.com/hello?ref=discord`
When these links are accessed admins can see how many time a link has been clicked based on the `ref` parameter. This is helpful to know where a shortened link was accessed.

### Motivation

Currently to do something similar you need to create duplicate short urls that all need to be unique. They also aren't dynamic. 
This is useful to see where traffic is coming from and where urls are possibly gaining traction.
Lastly, not every site or source will pass something of "referral" header so this is a great way to guarantee some method of tracking a link and its placement.

Site note: this is a feature on questionpro.com that i recently used and really liked being able to see where people were accessing a survey it put out giving me another piece of information into demographics.

### Describe the solution

Add a referral join-table
example:
<table>
<tr>
 <td>
 keyword
 <td>
ref
 <td>
count
<tr>
 <td>
hello
 <td>
discord
 <td>
4
<tr>
 <td>
hello
 <td>
qrcode
 <td>
3
</table>
And update UI to show break down based on ref param

**Comment by LeoColomb** [comment]
Thanks for opening this issue @jaredkotoff.
Isn't this something manageable with a plugin?

**Comment by jaredkotoff** [comment]
It could be, but it's also somewhat common feature of other url shortens.

And unless the database scheme has a place to track this sort of thing, I didn't see anything in the docs about plug-ins making changes to the database.  Wasn't sure if that was frowned upon.

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
In my opinion a referring parameter would be a value-add to core. Personally it would provide me more meaningful data than having location stats.

**Comment by ozh** [comment]
Sorry I'm a bit late in the discussion. What is @YOURLS/core thoughts about this ?

I'm definitely gettting "plugin territory" vibes on this one, I don't think this is something 99% of users need. It kinda defeats the "short URL" concept to *add* stuff to your short URL. It's been years and hundreds of thousands of YOURLS installs, and this is the first time this feature is requested.

**Comment by dgw** [comment]
Likely not the first time someone's wanted it, but I agree it sounds like plugin territory.

**Comment by jaredkotoff** [comment]
> this is the first time this feature is requested.

Im surprised no one has wanted UTM params before.

Is there documentation for modifing the db for plug-ins?

**Comment by ozh** [comment]
There have been a couple Google Analytics plugins, see https://github.com/YOURLS/awesome

There is no documentation for modifying the DB in plugins. A couple of them do it. It's just a matter of performing a SQL request. I would rely on the "plugin_$(plugin-name)" hook to create or alter tables, to make sure it's done once only. See for instance https://github.com/YOURLS/cache-stats-pages/blob/master/plugin.php#L48-L55

**Comment by sbarbieri** [comment]
Hi @jaredkotoff 

if you set the parameter 'YOURLS_UNIQUE_URLS' to false in the file user/config.php you are able to create duplicate urls but with different short code urls: I am using this to track the same URL but with different short urls. Then I generate QR Codes to better understand from which print product (poster, catalog etc.) users are coming or if for example poster qr codes are scanned i.e. are qr codes something people do really scan ;)

cheers

**Comment by jaredkotoff** [comment]
@sbarbieri i mention how this is not a viable solution. It's cumbersome and doesn't solve the need to create them on the fly. 
It also makes it hard to compare the traffic sources. 

Anyways, Im already working on the plug-in

**Comment by sandeep2rawat** [comment]
Had same requirement; so implemented a plugin
anyone having similar requirement can check it here 

https://github.com/sandeep2rawat/yourls-plugins/tree/main/track-ref-param
